# .readthedocs.yml  -- Read the Docs build configuration ------------------
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  # Optional: run extra commands *before* the documentation build.
  # Uncomment if you want to regenerate API .rst files every build.
  # jobs:
  #   pre_build:
  #     - >
  #       sphinx-apidoc -o docs/source/api/ -e -M -f fusionlab \
  #                     fusionlab/tests/* fusionlab/data/* ;
  #       echo "API stubs refreshed."

python:
  install:
    - requirements: docs/requirements.txt 
    - method: pip
      path: . # Installs the fusionlab package itself if required for docs
    #   extra_requirements:
    #     - dev # Installs dev dependencies if specified in setup.py/pyproject.toml
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false   # flip to true to make warnings fatal

# formats:
#   - pdf
#   - epub
