# .readthedocs.yml
# Read the Docs configuration file v2
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10" # Or "3.8", "3.9", "3.11" - match the project needs
  # jobs:
  #   pre_build:
  #     # Generate API documentation before building
  #     # Adjust paths relative to the project root:
  #     # -o <output_path_for_rst_files>
  #     # <path_to_your_package>
  #     # [paths_to_exclude...]
  #     - >
  #       sphinx-apidoc -o docs/source/api/ -e -M -f fusionlab fusionlab/tests/* fusionlab/data/*;
  #       echo "Generated API documentation using sphinx-apidoc."

# Optionally build the docs in additional formats such as PDF/ePub
# formats:
#  - pdf
#  - epub

# Declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt 
    # - method: pip
    #   path: . # Installs the fusionlab package itself if required for docs
    #   extra_requirements:
    #     - dev # Installs dev dependencies if specified in setup.py/pyproject.toml

# Build documentation using Sphinx
sphinx:
  configuration: docs/source/conf.py
  # Make the build fail if there are warnings
  fail_on_warning: False