# .github/workflows/python-package-conda.yml
# Workflow for FusionLab using Conda

name: Python Package using Conda (FusionLab)

# Trigger on pushes to main/develop and pull requests targeting main/develop
on:
  push:
    branches:
      - main
      - develop # Add other branches if needed
  pull_request:
    branches:
      - main
      - develop # Add other branches if needed

jobs:
  build-test-linux: # Renamed job for clarity
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # Use login shell for conda activation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Use latest checkout action

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3 # Use latest setup action
      with:
        activate-environment: fusionlab-dev # Use the correct env name
        environment-file: environment.yml # Point to your env file
        python-version: "3.10" # Specify Python version (must be compatible with env file)
        auto-activate-base: false
        # Conda configuration options can be added here if needed later
        # channel-priority: strict

    - name: Install FusionLab package
      run: |
        python -m pip install . --no-deps --force-reinstall
        # --no-deps: Assume conda handled dependencies
        # --force-reinstall: Ensure local package overwrites any cached version

    - name: Lint with flake8
      run: |
        echo "Running flake8 linter..."
        # Max line length 88 is common (used by Black formatter
